/** 공식 서비스 API HTML에서 추출한 Dooray REST 엔드포인트 목록. */
export const DOORAY_API_ENDPOINTS = [
  { section: "Common > Members", spec: "GET /common/v1/members" },
  { section: "Common > Members", spec: "GET /common/v1/members/{member-id}" },
  { section: "Common > Members", spec: "GET /common/v1/members/me" },
  { section: "Common > IncomingHooks", spec: "POST /common/v1/incoming-hooks" },
  { section: "Common > IncomingHooks", spec: "GET /common/v1/incoming-hooks/{incoming-hook-id}" },
  { section: "Common > IncomingHooks", spec: "DELETE /common/v1/incoming-hooks/{incoming-hook-id}" },
  { section: "Common > Streams", spec: "GET /common/v1/streams" },
  { section: "Project > Category", spec: "GET /project/v1/project-categories" },
  { section: "Project > Projects", spec: "POST /project/v1/projects" },
  { section: "Project > Projects", spec: "GET /project/v1/projects" },
  { section: "Project > Projects", spec: "GET /project/v1/projects/{project-id}" },
  { section: "Project > Projects", spec: "PUT /project/v1/projects/{project-id}" },
  { section: "Project > Projects", spec: "POST /project/v1/projects/{project-id}/set-archive" },
  { section: "Project > Projects", spec: "POST /project/v1/projects/{project-id}/set-active" },
  { section: "Project > Projects", spec: "POST /project/v1/projects/is-creatable" },
  { section: "Project > Projects > Workflows", spec: "GET /project/v1/projects/{project-id}/workflows" },
  { section: "Project > Projects > Workflows", spec: "POST /project/v1/projects/{project-id}/workflows" },
  { section: "Project > Projects > Workflows", spec: "PUT /project/v1/projects/{project-id}/workflows/{workflow-id}" },
  { section: "Project > Projects > Workflows", spec: "POST /project/v1/projects/{project-id}/workflows/{workflow-id}/delete" },
  { section: "Project > Projects > EmailAddress", spec: "POST /project/v1/projects/{project-id}/email-addresses" },
  { section: "Project > Projects > EmailAddress", spec: "GET /project/v1/projects/{project-id}/email-addresses/{email-address-id}" },
  { section: "Project > Projects > Tags", spec: "POST /project/v1/projects/{project-id}/tags" },
  { section: "Project > Projects > Tags", spec: "GET /project/v1/projects/{project-id}/tags" },
  { section: "Project > Projects > Tags", spec: "GET /project/v1/projects/{project-id}/tags/{tag-id}" },
  { section: "Project > Projects > Tags", spec: "PUT /project/v1/projects/{project-id}/tag-groups/{id}" },
  { section: "Project > Projects > Milestones", spec: "POST /project/v1/projects/{project-id}/milestones" },
  { section: "Project > Projects > Milestones", spec: "GET /project/v1/projects/{project-id}/milestones" },
  { section: "Project > Projects > Milestones", spec: "GET /project/v1/projects/{project-id}/milestones/{milestone-id}" },
  { section: "Project > Projects > Milestones", spec: "PUT /project/v1/projects/{project-id}/milestones/{milestone-id}" },
  { section: "Project > Projects > Milestones", spec: "DELETE /project/v1/projects/{project-id}/milestones/{milestone-id}" },
  { section: "Project > Projects > Hooks", spec: "POST /project/v1/projects/{project-id}/hooks" },
  { section: "Project > Projects > Members", spec: "POST /project/v1/projects/{project-id}/members" },
  { section: "Project > Projects > Members", spec: "GET /project/v1/projects/{project-id}/members" },
  { section: "Project > Projects > Members", spec: "GET /project/v1/projects/{project-id}/members/{member-id}" },
  { section: "Project > Projects > Members", spec: "DELETE /project/v1/projects/{project-id}/members/{member-id}" },
  { section: "Project > Projects > MemberGroups", spec: "GET /project/v1/projects/{project-id}/member-groups" },
  { section: "Project > Projects > MemberGroups", spec: "GET /project/v1/projects/{project-id}/member-groups/{member-group-id}" },
  { section: "Project > Projects > Template", spec: "POST /project/v1/projects/{project-id}/templates" },
  { section: "Project > Projects > Template", spec: "GET /project/v1/projects/{project-id}/templates" },
  { section: "Project > Projects > Template", spec: "GET /project/v1/projects/{project-id}/templates/{template-id}" },
  { section: "Project > Projects > Template", spec: "PUT /project/v1/projects/{project-id}/templates/{template-id}" },
  { section: "Project > Projects > Template", spec: "DELETE /project/v1/projects/{project-id}/templates/{template-id}" },
  { section: "Project > Posts", spec: "GET /project/v1/posts/{post-id}" },
  { section: "Project > Posts", spec: "POST /project/v1/post-drafts" },
  { section: "Project > Posts", spec: "POST /project/v1/post-drafts/{post-draft-id}/files" },
  { section: "Project > Projects > Posts", spec: "POST /project/v1/projects/{project-id}/posts" },
  { section: "Project > Projects > Posts", spec: "GET /project/v1/projects/{project-id}/posts" },
  { section: "Project > Projects > Posts", spec: "GET /project/v1/projects/{project-id}/posts/{post-id}" },
  { section: "Project > Projects > Posts", spec: "PUT /project/v1/projects/{project-id}/posts/{post-id}" },
  { section: "Project > Projects > Posts", spec: "PUT /project/v1/projects/{project-id}/posts/{post-id}/to/{organization-member-id}" },
  { section: "Project > Projects > Posts", spec: "POST /project/v1/projects/{project-id}/posts/{post-id}/set-workflow" },
  { section: "Project > Projects > Posts", spec: "POST /project/v1/projects/{project-id}/posts/{post-id}/set-done" },
  { section: "Project > Projects > Posts", spec: "POST /project/v1/projects/{project-id}/posts/{post-id}/set-parent-post" },
  { section: "Project > Projects > Posts", spec: "POST /project/v1/projects/{project-id}/posts/{post-id}/move" },
  { section: "Project > Projects > Posts", spec: "POST /project/v1/projects/{project-id}/posts/{post-id}/files" },
  { section: "Project > Projects > Posts", spec: "GET /project/v1/projects/{project-id}/posts/{post-id}/files" },
  { section: "Project > Projects > Posts", spec: "GET /project/v1/projects/{project-id}/posts/{post-id}/files/{file-id}?media=meta" },
  { section: "Project > Projects > Posts", spec: "GET /project/v1/projects/{project-id}/posts/{post-id}/files/{file-id}?media=raw" },
  { section: "Project > Projects > Posts", spec: "DELETE /project/v1/projects/{project-id}/posts/{post-id}/files/{file-id}" },
  { section: "Project > Projects > Posts > Logs", spec: "POST /project/v1/projects/{project-id}/posts/{post-id}/logs" },
  { section: "Project > Projects > Posts > Logs", spec: "GET /project/v1/projects/{project-id}/posts/{post-id}/logs" },
  { section: "Project > Projects > Posts > Logs", spec: "GET /project/v1/projects/{project-id}/posts/{post-id}/logs/{log-id}" },
  { section: "Project > Projects > Posts > Logs", spec: "PUT /project/v1/projects/{project-id}/posts/{post-id}/logs/{log-id}" },
  { section: "Project > Projects > Posts > Logs", spec: "DELETE /project/v1/projects/{project-id}/posts/{post-id}/logs/{log-id}" },
  { section: "Calendar > Calendars", spec: "POST /calendar/v1/calendars" },
  { section: "Calendar > Calendars", spec: "GET /calendar/v1/calendars" },
  { section: "Calendar > Calendars", spec: "GET /calendar/v1/calendars/{calendar-id}" },
  { section: "Calendar > Calendars", spec: "DELETE /calendar/v1/calendars/{calendar-id}" },
  { section: "Calendar > Calendars", spec: "PUT /calendar/v1/calendars/{calendar-id}/members" },
  { section: "Calendar > Calendars > Events", spec: "POST /calendar/v1/calendars/{calendar-id}/events" },
  { section: "Calendar > Calendars > Events", spec: "GET /calendar/v1/calendars/*/events" },
  { section: "Calendar > Calendars > Events", spec: "GET /calendar/v1/calendars/{calendar-id}/events/{event-id}" },
  { section: "Calendar > Calendars > Events", spec: "PUT /calendar/v1/calendars/{calendar-id}/events/{event-id}" },
  { section: "Calendar > Calendars > Events", spec: "POST /calendar/v1/calendars/{calendar-id}/events/{event-id}/delete" },
  { section: "Drive > Drives", spec: "GET /drive/v1/drives" },
  { section: "Drive > Drives", spec: "GET /drive/v1/drives/{drive-id}" },
  { section: "Drive > Drives", spec: "GET /drive/v2/drives/{drive-id}/changes" },
  { section: "Drive > Files", spec: "GET /drive/v1/files/{file-id}?media=meta" },
  { section: "Drive > Drives > Files", spec: "POST /drive/v1/drives/{drive-id}/files?parentId={}" },
  { section: "Drive > Drives > Files", spec: "GET /drive/v1/drives/{drive-id}/files" },
  { section: "Drive > Drives > Files", spec: "GET /drive/v1/drives/{drive-id}/files/{file-id}?media=meta" },
  { section: "Drive > Drives > Files", spec: "GET /drive/v1/drives/{drive-id}/files/{file-id}?media=raw" },
  { section: "Drive > Drives > Files", spec: "PUT /drive/v1/drives/{drive-id}/files/{file-id}?media=meta" },
  { section: "Drive > Drives > Files", spec: "PUT /drive/v1/drives/{drive-id}/files/{file-id}?media=raw" },
  { section: "Drive > Drives > Files", spec: "DELETE /drive/v1/drives/{drive-id}/files/{file-id}" },
  { section: "Drive > Drives > Files", spec: "POST /drive/v1/drives/{drive-id}/files/{folder-id}/create-folder" },
  { section: "Drive > Drives > Files", spec: "POST /drive/v1/drives/{drive-id}/files/{file-id}/copy" },
  { section: "Drive > Drives > Files", spec: "POST /drive/v1/drives/{drive-id}/files/{file-id}/move" },
  { section: "Drive > Drives > Files > SharedLinks", spec: "POST /drive/v1/drives/{drive-id}/files/{file-id}/shared-links" },
  { section: "Drive > Drives > Files > SharedLinks", spec: "GET /drive/v1/drives/{drive-id}/files/{file-id}/shared-links" },
  { section: "Drive > Drives > Files > SharedLinks", spec: "GET /drive/v1/drives/{drive-id}/files/{file-id}/shared-links/{link-id}" },
  { section: "Drive > Drives > Files > SharedLinks", spec: "PUT /drive/v1/drives/{drive-id}/files/{file-id}/shared-links/{link-id}" },
  { section: "Drive > Drives > Files > SharedLinks", spec: "DELETE /drive/v1/drives/{drive-id}/files/{file-id}/shared-links/{link-id}" },
  { section: "Wiki > Pages", spec: "GET /wiki/v1/wikis" },
  { section: "Wiki > Pages", spec: "GET /wiki/v1/pages/{page-id}" },
  { section: "Wiki > Pages", spec: "POST /wiki/v1/wikis/{wiki-id}/pages" },
  { section: "Wiki > Pages", spec: "GET /wiki/v1/wikis/{wiki-id}/pages" },
  { section: "Wiki > Pages", spec: "GET /wiki/v1/wikis/{wiki-id}/pages/{page-id}" },
  { section: "Wiki > Pages", spec: "PUT /wiki/v1/wikis/{wiki-id}/pages/{page-id}" },
  { section: "Wiki > Pages", spec: "PUT /wiki/v1/wikis/{wiki-id}/pages/{page-id}/title" },
  { section: "Wiki > Pages", spec: "PUT /wiki/v1/wikis/{wiki-id}/pages/{page-id}/content" },
  { section: "Wiki > Pages", spec: "PUT /wiki/v1/wikis/{wiki-id}/pages/{page-id}/referrers" },
  { section: "Wiki > Pages", spec: "POST /wiki/v1/wikis/{wiki-id}/pages/{page-id}/move" },
  { section: "Wiki > Pages", spec: "DELETE /wiki/v1/wikis/{wiki-id}/pages/{page-id}" },
  { section: "Wiki > Pages > Comments", spec: "POST /wiki/v1/wikis/{wiki-id}/pages/{page-id}/comments" },
  { section: "Wiki > Pages > Comments", spec: "GET /wiki/v1/wikis/{wiki-id}/pages/{page-id}/comments" },
  { section: "Wiki > Pages > Comments", spec: "GET /wiki/v1/wikis/{wiki-id}/pages/{page-id}/comments/{comment-id}" },
  { section: "Wiki > Pages > Comments", spec: "PUT /wiki/v1/wikis/{wiki-id}/pages/{page-id}/comments/{comment-id}" },
  { section: "Wiki > Pages > Comments", spec: "DELETE /wiki/v1/wikis/{wiki-id}/pages/{page-id}/comments/{comment-id}" },
  { section: "Wiki > Pages > SharedLinks", spec: "GET /wiki/v1/wikis/{wiki-id}/pages/{page-id}/shared-links" },
  { section: "Wiki > Attach Files", spec: "GET /wiki/v1/wikis/{wiki-id}/attachFiles/{attach-file-id}" },
  { section: "Wiki > Pages > Files", spec: "POST /wiki/v1/wikis/{wiki-id}/pages/{page-id}/files" },
  { section: "Wiki > Pages > Files", spec: "GET /wiki/v1/wikis/{wiki-id}/pages/{page-id}/files/{file-id}" },
  { section: "Wiki > Pages > Files", spec: "DELETE /wiki/v1/wikis/{wiki-id}/pages/{page-id}/files/{file-id}" },
  { section: "Wiki > Files", spec: "POST /wiki/v1/wikis/{wiki-id}/files" },
  { section: "Messenger > Channels", spec: "POST /messenger/v1/channels/direct-send" },
  { section: "Messenger > Channels", spec: "GET /messenger/v1/channels" },
  { section: "Messenger > Channels", spec: "POST /messenger/v1/channels?idType={email|member-id}" },
  { section: "Messenger > Channels", spec: "POST /messenger/v1/channels/{channel-id}/members/join" },
  { section: "Messenger > Channels", spec: "POST /messenger/v1/channels/{channel-id}/members/leave" },
  { section: "Messenger > Channels", spec: "POST /messenger/v1/channels/{channel-id}/logs" },
  { section: "Messenger > Channels", spec: "PUT /messenger/v1/channels/{channel-id}/logs/{log-id}" },
  { section: "Messenger > Channels", spec: "DELETE /messenger/v1/channels/{channel-id}/logs/{log-id}" },
  { section: "Messenger > Channels", spec: "POST /messenger/v1/channels/{channel-id}/logs/{log-id}/reply" },
  { section: "Messenger > Channels", spec: "POST /messenger/v1/channels/{channel-id}/threads/create-and-send" },
  { section: "Messenger > Channels", spec: "POST /messenger/v1/channels/{channel-id}/logs/{log-id}/threads/create-and-send" },
  { section: "Reservation > ResourcesCategory", spec: "GET /reservation/v1/resource-categories" },
  { section: "Reservation > Resources", spec: "GET /reservation/v1/resources" },
  { section: "Reservation > Resources", spec: "GET /reservation/v1/resources/{resource-id}" },
  { section: "Reservation > Resources", spec: "GET /reservation/v1/reservable-resources" },
  { section: "Reservation > Resource Reservations", spec: "GET /reservation/v1/resource-reservations" },
  { section: "Reservation > Resource Reservations", spec: "POST /reservation/v1/resource-reservations" },
  { section: "Reservation > Resource Reservations", spec: "GET /reservation/v1/resource-reservations/{resource-reservation-id}" },
  { section: "Reservation > Resource Reservations", spec: "PUT /reservation/v1/resource-reservations/{resource-reservation-id}" },
  { section: "Reservation > Resource Reservations", spec: "DELETE /reservation/v1/resource-reservations/{resource-reservation-id}" },
  { section: "Contact > Contacts", spec: "GET /contacts/v1/contacts" },
  { section: "Contact > Contacts", spec: "GET /contacts/v1/contacts/{contact-id}" },
  { section: "Contact > Contacts", spec: "POST /contacts/v1/contacts/search" },
] as const;

export function formatEndpointCatalog(): string {
  const groups = new Map<string, string[]>();
  for (const item of DOORAY_API_ENDPOINTS) {
    const list = groups.get(item.section) ?? [];
    list.push(item.spec);
    groups.set(item.section, list);
  }
  const parts: string[] = ['Dooray Service API endpoints (official spec):'];
  for (const [section, specs] of groups) {
    parts.push('', `## ${section}`);
    for (const spec of specs) parts.push(`- ${spec}`);
  }
  return parts.join('\n');
}
